github: [metadata]
encoding: UTF-8
 kramdown:
   input: GFM
   hard_wrap: false
 future: true
 jailed: false
 theme: jekyll-theme-primer
 gfm_quirks: paragraph_end

relative_links:
  enabled: true
  collections: true
include:
  - SQLandR.md
  - README.md
  - LICENSE.md
 

theme: jekyll-theme-minimal

